import type { HostingLocationData } from "@/components/hosting-location-page";

export const hostingLocations: Record<string, HostingLocationData> = {
  "asheville": {
    city: "Asheville",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "asheville",
    heroTagline: "A great wedding in Asheville feels like the mountains themselves — layered, unhurried, and completely alive. The best hosting honors that rhythm and keeps the room breathing together.",
    introParagraph: "Asheville couples tend to know exactly who they are, and they build celebrations that reflect it. I work within that vision — not over it. The crowds here are often eclectic: artists, mountain families, out-of-town guests discovering each other for the first time. My job is to give those people a shared language for the night. In a city that values authenticity above almost anything else, the hosting has to feel earned, not performed.",
    regionDescription: "The Blue Ridge Parkway corridor has become one of the most sought-after wedding destinations in the Southeast, drawing couples who want scenery and substance in equal measure. Asheville's wedding culture is independent-minded — couples here resist templates, which means the hosting has to be genuinely responsive to the room rather than following a script.",
    venues: [
      { name: "The Omni Grove Park Inn", location: "Asheville, NC", description: "A grand historic resort with sweeping mountain views; its ballroom carries formal energy that rewards a confident host who can soften the grandeur without losing the elegance." },
      { name: "Biltmore Estate", location: "Asheville, NC", description: "The scale here — multiple rooms, vast lawns, and a castle backdrop — requires a host who can hold attention across transitions and keep guests anchored through the movement of the evening." },
      { name: "The Crest Center and Pavilion", location: "Asheville, NC", description: "A hilltop event center with panoramic ridgeline views; the open layout means program flow depends heavily on how the host manages sightlines and crowd attention during key moments." },
      { name: "Highland Brewing Company", location: "Asheville, NC", description: "An industrial-chic venue with an outdoor amphitheater feel; the informal energy here calls for hosting that leans casual and conversational rather than ceremonial." },
      { name: "Venue 1889", location: "Asheville, NC", description: "A restored Victorian building in the heart of the city with intimate rooms that make every toast feel personal and close — low ambient noise means the host's voice carries cleanly." },
      { name: "The Inn on Biltmore Estate", location: "Asheville, NC", description: "An upscale hotel venue attached to the estate grounds; guests expect polish and precision, and the hosting tempo needs to match the deliberate elegance of the space." },
      { name: "Honeysuckle Hill Events", location: "Asheville, NC", description: "A 9-acre private estate with a century-old red barn and hayloft chapel where the intimate farm setting rewards a host who can move the room personally and let the evening breathe." },
      { name: "Chestnut Ridge", location: "Asheville, NC", description: "A modern mountain-meets-farm estate with wide-open views where the flow between outdoor and indoor spaces requires a host who can maintain energy across multiple settings." },
    ],
    nearbyAreas: ["Weaverville", "Black Mountain", "Swannanoa", "Arden", "Fletcher", "Fairview", "Mars Hill"],
    faq: [
      { question: "What does an MC actually do at a wedding?", answer: "An MC is the connective tissue of the evening. I handle all announcements and transitions, but more importantly, I set the tone for each moment — warming the room before toasts, building energy before the first dance, giving guests permission to relax. A good host makes everything feel inevitable rather than scheduled." },
      { question: "How do you handle toasts so they land?", answer: "I work with speakers beforehand to understand what they want to say, then I frame each toast for the room before the speaker stands up. That context is what makes a toast land — guests are already emotionally primed. I also stay close in case someone needs a quiet redirect if things run long." },
      { question: "Can you incorporate bilingual or multicultural elements into the hosting?", answer: "Yes. I have background in Slavic wedding traditions and I build custom programs around whatever cultural touchstones matter to the couple. Whether that means specific toasting rituals, translated moments, or honoring family customs, those elements get woven into the flow — not treated as interruptions to it." },
    ],
  },
  "boone": {
    city: "Boone",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "boone",
    heroTagline: "High-country weddings in Boone carry a particular warmth — the elevation, the mist, the sense of being above the noise of the world. Great hosting lets the room feel that without anyone having to explain it.",
    introParagraph: "Boone sits at nearly 3,400 feet, and the couples who marry here tend to choose it deliberately. They want something different from a hotel ballroom in the flatlands. I bring hosting that honors that choice — grounded, unhurried, attentive to the particular mix of Appalachian families and Appalachian State graduates and city visitors who often fill these rooms. The culture here values directness and sincerity, which means I keep the hosting real.",
    regionDescription: "The High Country of northwestern North Carolina has a distinct wedding identity shaped by Appalachian roots, a strong university presence, and dramatic seasonal scenery. Couples here often have deep family ties to the region, which means the hosting has to respect those roots while creating space for everyone in the room.",
    venues: [
      { name: "Meadowbrook Inn", location: "Blowing Rock, NC", description: "A charming mountain inn near Boone with intimate indoor and garden spaces that reward a host who can shift between quiet personal moments and energetic celebration without jarring the room." },
      { name: "Chetola Resort", location: "Blowing Rock, NC", description: "A lakeside resort with ballroom and outdoor options; the varied spaces here mean the host has to manage guest movement between settings and maintain energy across the transitions." },
      { name: "Appalachian Ski Mountain Event Center", location: "Blowing Rock, NC", description: "A scenic mountain venue that tends to attract adventurous couples and social crowds who respond well to a host willing to take risks with crowd work and humor." },
      { name: "Banner Elk Winery", location: "Banner Elk, NC", description: "An intimate vineyard venue where the informal rustic setting invites a conversational hosting style — guests here tend to be relaxed and open from the moment they arrive." },
      { name: "The Hound Ears Club", location: "Boone, NC", description: "A private club setting with a refined mountain aesthetic; the membership clientele expects understated elegance, and the hosting needs to match that tone precisely." },
      { name: "Grandfather Vineyard and Winery", location: "Banner Elk, NC", description: "A winery venue framed by Grandfather Mountain views where the outdoor-to-indoor flow of the evening requires a host who can read weather-driven energy shifts gracefully." },
      { name: "Valle Crucis Conference Center", location: "Valle Crucis, NC", description: "A historic riverside camp with a communal retreat-like feel that lends itself to hosting that builds community rather than performing — guests here want to be brought in, not talked at." },
    ],
    nearbyAreas: ["Blowing Rock", "Banner Elk", "Valle Crucis", "West Jefferson", "Newland", "Lenoir", "Jefferson"],
    faq: [
      { question: "Do you write custom scripts for each wedding?", answer: "Every program is built from scratch for the couple. I learn your names, your story, how you met, what your families are like, and what you care about for the evening. What gets said in the room reflects your specific celebration — not a template filled in with your names." },
      { question: "How do you handle a room with very different guest demographics?", answer: "I find the universal threads — humor that doesn't alienate, stories that both grandmothers and college friends can feel — and I build bridges between the groups rather than playing to one side." },
      { question: "What if we want the evening to feel relaxed and not overly produced?", answer: "Invisible hosting is the hardest kind and the most valuable. If everything flows naturally and no one feels managed, that's not an accident — it's the result of a lot of preparation done quietly beforehand." },
    ],
  },
  "brevard": {
    city: "Brevard",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "brevard",
    heroTagline: "Brevard weddings exist at the edge of the wild — Pisgah Forest at the door, waterfalls within walking distance. The best hosting channels that quiet magnificence and lets the room feel it together.",
    introParagraph: "Brevard is a small city with a surprisingly sophisticated arts and music culture — the Brevard Music Center draws world-class musicians every summer. The couples who marry here often have refined taste layered over genuine mountain roots. I meet that combination with hosting that is precise without being stiff, warm without being sentimental. The guest mix here tends to include artists, academics, and old-family mountain folk in the same room, and I find that tension generative.",
    regionDescription: "Transylvania County has become a destination for couples drawn to the combination of accessible infrastructure and genuine wilderness. Brevard's identity as the 'Land of Waterfalls' and its proximity to Pisgah National Forest shape a wedding culture that values authenticity and natural beauty over conventional formality.",
    venues: [
      { name: "The Cedars of Brevard", location: "Brevard, NC", description: "A sprawling mountain estate with multiple ceremony and reception settings where the host's ability to guide guests through different spaces determines whether the evening feels cohesive or disjointed." },
      { name: "Camp Ton-A-Wandah", location: "Brevard, NC", description: "A lakeside camp venue with rustic charm; the open-air setting rewards a host who can hold attention without the acoustic support of a traditional reception hall." },
      { name: "The Inn at Brevard", location: "Brevard, NC", description: "A Victorian-era bed and breakfast with small intimate reception spaces where the host works in close quarters — every word lands at close range, which requires a conversational and less amplified style." },
      { name: "Sherwood Forest Camp", location: "Brevard, NC", description: "A private camp facility in the Pisgah Forest corridor that suits couples who want their celebration to feel like a gathering among friends rather than a formal event." },
      { name: "Seven Maples", location: "Brevard, NC", description: "A rolling farm property bordered by a creek with a barn and open ceremony field where the natural setting invites unhurried, heartfelt hosting." },
      { name: "Looking Glass Falls area private estates", location: "Transylvania County, NC", description: "Private mountain estate rentals near the waterfall corridors where no two venues are alike — the host must be fully adaptable to the unique geometry and flow of each space." },
    ],
    nearbyAreas: ["Hendersonville", "Asheville", "Rosman", "Pisgah Forest", "Cedar Mountain", "Lake Toxaway", "Sapphire"],
    faq: [
      { question: "How do you handle outdoor weddings where sound and attention are harder to control?", answer: "Outdoor ceremonies and receptions require more deliberate pacing and sharper awareness of where people are looking and whether they can hear. I work closely with the sound engineer to make sure coverage is right, and I structure the program to maintain focus without forcing it." },
      { question: "What does it mean that your hosting comes from the Slavic tamada tradition?", answer: "In that tradition, the wedding host is not an announcer — they are the emotional center of the celebration. Their job is to create moments, connect people who don't know each other, and hold the energy of the room across hours. It is a craft that takes a long time to develop and cannot be faked." },
      { question: "Do you coordinate with the catering and venue staff?", answer: "Yes. Before every wedding I connect with the venue coordinator, caterer, and photographer to map out the evening's timing. On the day itself, I am the central communication point for program-related timing so the announcements and flow align with what is happening on the floor." },
    ],
  },
  "charlotte": {
    city: "Charlotte",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "charlotte",
    heroTagline: "Charlotte weddings move at the pace of a confident city — polished, ambitious, full of people who have high standards and can tell the difference. The hosting has to match that without feeling corporate.",
    introParagraph: "Charlotte is the largest city in the Carolinas, and its wedding market reflects that scale — there is serious money here, serious taste, and guests who attend a lot of weddings and notice everything. I bring hosting that is clean and precise, never fussy. The couples I work with in Charlotte tend to want a seamless evening that their guests rave about without being able to articulate why — that invisible, frictionless quality is what I am after.",
    regionDescription: "Charlotte's wedding industry is one of the most competitive in the South, with a client base that includes finance professionals, entrepreneurs, and families with genuine sophistication about what good service looks like. The hosting standard here is high, and couples rightfully expect someone who can command a room of two hundred and make it feel personal.",
    venues: [
      { name: "The Mint Museum Uptown", location: "Charlotte, NC", description: "A stunning art museum venue in the heart of Uptown with gallery-lined reception halls where hosting must be refined and restrained, letting the space and the art share the room." },
      { name: "The Ritz-Carlton Charlotte", location: "Charlotte, NC", description: "A flagship luxury hotel ballroom where guests arrive with high expectations; the hosting needs to deliver polish from the first word and manage a sophisticated crowd's attention without condescension." },
      { name: "The Ivey's Hotel", location: "Charlotte, NC", description: "A boutique hotel in a restored 1924 department store with intimate design-forward event spaces where hosting can be more personal and textured than in larger ballroom settings." },
      { name: "SouthEnd Loft spaces", location: "Charlotte, NC", description: "Industrial-chic loft venues in the SouthEnd corridor attract younger trend-conscious couples whose guests expect a host with personality and cultural awareness rather than formal ceremony." },
      { name: "Duke Mansion", location: "Charlotte, NC", description: "A historic 1915 estate in the Myers Park neighborhood where the Southern legacy of the space calls for hosting that honors tradition while keeping the evening from feeling stuffy." },
      { name: "Carmel Country Club", location: "Charlotte, NC", description: "A classic country club setting where member families often make up a significant portion of the guest list — the host navigates familiarity and formality simultaneously." },
      { name: "The Ballantyne Hotel", location: "Charlotte, NC", description: "A resort-style hotel in south Charlotte with expansive ballrooms where large wedding parties require clear, confident hosting to maintain program momentum." },
      { name: "Foundation for the Carolinas", location: "Charlotte, NC", description: "A premier civic event space with grand architecture where managing the scale of large receptions requires a host who can project authority without amplifying ego." },
    ],
    nearbyAreas: ["Mooresville", "Concord", "Huntersville", "Matthews", "Gastonia", "Monroe", "Rock Hill, SC"],
    faq: [
      { question: "How do you handle large weddings with 200 or more guests?", answer: "Scale changes what works. With large rooms, the hosting becomes more precise — shorter, more clearly structured moments, sharper transitions, stronger setup before each beat. A large crowd is actually easier to move emotionally than a small one, as long as the timing is right." },
      { question: "Can you host a wedding that mixes formal and casual elements?", answer: "Most great weddings do exactly that. The key is understanding which moments call for which register and making the shifts feel natural. I map that in advance with the couple and then stay flexible on the night based on how the room is actually responding." },
      { question: "What sets a good MC apart from someone who just reads announcements?", answer: "An announcer manages logistics. An MC manages energy. What I do is closer to conducting — I read the emotional temperature of the room continuously and shape each moment to land at the right weight. Guests feel the difference even if they cannot name it." },
    ],
  },
  "columbia-sc": {
    city: "Columbia",
    state: "South Carolina",
    stateAbbr: "SC",
    slug: "columbia-sc",
    heroTagline: "Columbia weddings carry the weight of deep Southern tradition and the energy of a capital city that never quite slows down. Great hosting holds both — the ceremony of it and the life underneath.",
    introParagraph: "Columbia is a city of layers — the state capital, a major university town, a military hub, and a deep-rooted Southern community all at once. The guest lists I encounter here reflect that complexity. I bring hosting that is confident enough for the formal Southern reception and flexible enough for the USC crowd that wants to feel something real. The hospitality culture here is strong, which means guests arrive with a frame of reference and notice when the hosting rises above it.",
    regionDescription: "The Midlands of South Carolina have a wedding culture rooted in antebellum tradition, strong family networks, and a pride of place that runs deep. Columbia couples often have guest lists that span multiple generations of the same families, which means the hosting has to create bridges across those generations without losing either end.",
    venues: [
      { name: "The Palmetto Club", location: "Columbia, SC", description: "A historic private club in downtown Columbia with formal reception spaces where Southern formality is the baseline expectation and the hosting must honor that without feeling dated." },
      { name: "The Venue at Gervais", location: "Columbia, SC", description: "A downtown loft-style event space on the Congaree River corridor that attracts younger couples and creative professionals who want a host with presence and personality." },
      { name: "The Inn at USC Wyndham Garden", location: "Columbia, SC", description: "A polished hotel venue adjacent to the University of South Carolina campus where alumni and academic communities often intersect — the host must be comfortable with an educated, opinion-strong crowd." },
      { name: "Riverbanks Zoo and Garden event spaces", location: "Columbia, SC", description: "Botanical and garden event settings where the outdoor-to-indoor flow of the evening requires a host who can keep energy consistent across unusual and visually dynamic environments." },
      { name: "The Reserve at Lake Murray", location: "Chapin, SC", description: "A lakeside country club venue outside Columbia where the relaxed waterfront setting and club culture shape a crowd that wants elegance without rigidity." },
      { name: "Saluda's Restaurant event space", location: "Columbia, SC", description: "An intimate upscale venue on a hill overlooking the city where smaller guest counts allow a host to work at close range and let the program breathe." },
    ],
    nearbyAreas: ["Lexington", "Irmo", "Chapin", "Camden", "Sumter", "Orangeburg", "Newberry"],
    faq: [
      { question: "How do you approach hosting for deeply traditional Southern families?", answer: "I respect the traditions that matter to the family without treating the evening like a museum piece. Southern wedding culture has genuine warmth and ritual at its core, and I work within that rather than against it. If the blessing before dinner is important, I set it up properly." },
      { question: "Can you host a wedding with a very formal dinner program?", answer: "Yes. Formal programs require precise timing and clean transitions between courses, speakers, and dances. I work with the catering team in advance to align the hosting beats with the service rhythm. The goal is a program that feels curated and unhurried, not rushed by the kitchen." },
      { question: "Do you handle the introduction of the wedding party?", answer: "Yes, and I treat grand entrances as a moment to build energy rather than just recite names. I work with the couple beforehand to understand relationships and personalities so I can give each person in the party a proper introduction — one that lands as a moment, not a formality." },
    ],
  },
  "gatlinburg": {
    city: "Gatlinburg",
    state: "Tennessee",
    stateAbbr: "TN",
    slug: "gatlinburg",
    heroTagline: "A Gatlinburg wedding happens in one of the most dramatic landscapes in the East — the Smokies pressing in from all sides. The hosting grounds the celebration so the beauty of the setting becomes part of the story, not a distraction from it.",
    introParagraph: "Gatlinburg is one of the most visited wedding destinations in the country, and that means the market runs wide — from casual elopements to elaborate mountain celebrations. I work primarily with couples who want the latter: a real, full reception where the hosting matches the setting. Tennessee couples and their guests tend to be warm, expressive, and unafraid of sentiment — which is exactly the kind of room I love hosting.",
    regionDescription: "The Great Smoky Mountains corridor from Gatlinburg through Pigeon Forge and into Sevier County hosts thousands of weddings annually. The cultural mix here — Appalachian families, Southern hospitality, and destination guests from across the country — creates rooms that require a host with genuine range.",
    venues: [
      { name: "Park Vista – A DoubleTree by Hilton Hotel", location: "Gatlinburg, TN", description: "A large hotel perched above Gatlinburg with panoramic Smoky Mountain views; the ballroom spaces draw couples who want mountain scenery without sacrificing hotel-level service, and the hosting needs to match that polished-but-approachable register." },
      { name: "Buckberry Lodge", location: "Gatlinburg, TN", description: "A luxury mountain lodge with intimate rustic-elegant event spaces where the small-group feel allows a host to be more personal and storytelling-forward in their approach." },
      { name: "Westgate Smoky Mountain Resort", location: "Gatlinburg, TN", description: "A large resort with multiple event venues where destination wedding guests often arrive already in celebration mode — the host channels that energy rather than starting from zero." },
      { name: "Greystone Estate", location: "Sevierville, TN", description: "A private estate venue near Gatlinburg with outdoor ceremony spaces and elegant indoor reception rooms where managing the outdoor-to-indoor guest transition is one of the host's key roles." },
      { name: "The Foxtrot — A Mountain Inn", location: "Gatlinburg, TN", description: "A boutique mountain inn with smaller reception capacity where the host works in close proximity to guests and the program can be flexible and responsive in real time." },
      { name: "The Gatlinburg Convention Center", location: "Gatlinburg, TN", description: "A large-scale event space in the heart of Gatlinburg suited for bigger receptions where the host must manage crowd energy across a wide physical space." },
    ],
    nearbyAreas: ["Pigeon Forge", "Sevierville", "Knoxville", "Cosby", "Cherokee NC", "Townsend", "Maryville"],
    faq: [
      { question: "How do you handle destination weddings where guests don't know each other?", answer: "Destination weddings are where hosting matters most. When guests have traveled from different cities and don't share a common social network, the host is what connects them. I build in intentional moments early in the evening that give strangers a reason to talk — structured toasts, short rituals, introductions that create threads between tables." },
      { question: "What if the couple wants a very short, simple program?", answer: "Short programs are harder to host than long ones, because every moment has to count. I can run an efficient evening that covers the essentials without ever feeling rushed. The key is preparation — knowing exactly what matters to the couple and executing those moments cleanly." },
      { question: "Do you work with the ceremony officiant as well?", answer: "My focus is the reception. That said, I coordinate with the officiant on timing so the handoff from ceremony to cocktail hour to reception is smooth. The transition into the reception is a critical moment, and I am always positioned to catch the energy as guests arrive." },
    ],
  },
  "greensboro": {
    city: "Greensboro",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "greensboro",
    heroTagline: "Greensboro weddings are shaped by a city that takes pride seriously — community, family, and a long memory for what things should feel like at their best. The hosting has to earn that room's trust.",
    introParagraph: "Greensboro sits at the heart of the Piedmont Triad, and its wedding culture reflects the deep community ties of a mid-sized Southern city where everyone seems to know everyone. Guest lists here often read like a map of the entire extended family and half the workplace — which means the hosting has to navigate familiarity with care. I bring precision and warmth in equal measure, which is exactly what rooms like this require.",
    regionDescription: "The Piedmont Triad — Greensboro, Winston-Salem, and High Point — shares a wedding culture rooted in Carolinian family tradition. Greensboro in particular has a strong tradition with high standards for ceremony, meaning the hosting must be culturally aware and consistently excellent.",
    venues: [
      { name: "Proximity Hotel", location: "Greensboro, NC", description: "A LEED-certified boutique luxury hotel with sophisticated event spaces and a design-forward aesthetic that attracts couples with refined taste and guests who notice quality." },
      { name: "The Grandover Resort", location: "Greensboro, NC", description: "A large resort and conference center with expansive ballrooms suited for big receptions; the scale requires a host who can command a wide room and keep the program tight across long distances." },
      { name: "The Carolina Theatre", location: "Greensboro, NC", description: "A 1927 theater-turned-event venue with dramatic architecture where the theatrical setting invites a host to be a little more expressive and performative than in a conventional ballroom." },
      { name: "Greensboro Country Club", location: "Greensboro, NC", description: "A traditional private club where the membership culture and multigenerational guest lists call for hosting that is formal, gracious, and respectful of convention." },
      { name: "LeBauer Park", location: "Greensboro, NC", description: "A downtown park venue used for outdoor receptions where the host manages the open environment and creates cohesion in a space that does not have four walls to contain the energy." },
      { name: "Greensboro Arboretum event spaces", location: "Greensboro, NC", description: "Garden and outdoor event spaces in a botanical setting where natural beauty provides the backdrop and the host's job is to complement rather than compete with the environment." },
    ],
    nearbyAreas: ["Winston-Salem", "High Point", "Burlington", "Asheboro", "Reidsville", "Archdale", "Graham"],
    faq: [
      { question: "How do you keep a large family-centered Southern reception from feeling chaotic?", answer: "Structure and respect. I build a clear program timeline and stick to it, but I also know which moments in a Southern reception need extra room to breathe — the blessing, the first dances, the toasts from parents. The chaos comes when those moments arrive without preparation." },
      { question: "Can you host a wedding with a strong faith component?", answer: "Yes. I work within whatever faith tradition matters to the couple and their family. If the blessing before dinner needs to be a specific person or prayer, I coordinate that in advance. I do not impose or omit — I follow the couple's lead." },
      { question: "How far in advance do you meet with us to plan the program?", answer: "I typically schedule a detailed planning conversation four to eight weeks before the wedding, and a final check-in one week out. But I am available by message throughout the planning process whenever questions come up." },
    ],
  },
  "greenville-sc": {
    city: "Greenville",
    state: "South Carolina",
    stateAbbr: "SC",
    slug: "greenville-sc",
    heroTagline: "Greenville has become one of the South's most admired small cities, and its wedding scene has grown to match — sophisticated, diverse, and deeply invested in getting things right. The hosting has to keep up.",
    introParagraph: "Greenville, South Carolina has undergone a remarkable transformation over the past two decades, and it shows in its weddings. The couples here are often professionals who have relocated from larger cities, mixed with deep Upstate South Carolina families, and the combination creates guest lists with real range. I bring hosting that reads that room accurately — finding the register that works for both the transplanted Brooklynite and the grandmother who has lived on the same county road for sixty years.",
    regionDescription: "The Upstate South Carolina corridor centered on Greenville has emerged as one of the South's most dynamic wedding markets, with a client base that blends Southern tradition with cosmopolitan expectations. The BMW manufacturing presence and influx of international business have added genuine cultural diversity to what was once a more homogeneous region.",
    venues: [
      { name: "The Westin Poinsett", location: "Greenville, SC", description: "A landmark 1925 luxury hotel on Main Street with grand ballrooms and Southern character; the historic setting carries its own weight and the hosting should honor the elegance without being stiff." },
      { name: "Larkins on the River", location: "Greenville, SC", description: "A riverside event venue with views of Falls Park where the natural drama of the location sets a high bar and the host must match it with equally memorable moments." },
      { name: "The Old Cigar Warehouse", location: "Greenville, SC", description: "A converted industrial space in the West End with brick walls and high ceilings that creates dramatic visual texture — the host must match that energy with presence and pacing." },
      { name: "The Gather Greene", location: "Greenville, SC", description: "A downtown event space with an industrial-modern aesthetic that attracts younger, design-conscious couples whose guests respond best to a host who is sharp and current." },
      { name: "Thornblade Club", location: "Greer, SC", description: "A private country club northeast of Greenville where the established membership culture and multigenerational guest lists expect a polished, traditional hosting approach." },
      { name: "Swamp Rabbit Inn", location: "Travelers Rest, SC", description: "A boutique outdoor-focused venue along the Swamp Rabbit Trail north of Greenville where the adventure-outdoor aesthetic calls for casual, conversational hosting." },
      { name: "Soby's on the Side", location: "Greenville, SC", description: "An intimate event space attached to one of Greenville's landmark restaurants where the food culture is central and the host works within a setting where the evening's pleasures are deliberate and curated." },
    ],
    nearbyAreas: ["Spartanburg", "Anderson", "Easley", "Greer", "Travelers Rest", "Simpsonville", "Mauldin"],
    faq: [
      { question: "How do you handle multicultural weddings with guests from different countries?", answer: "I map the cultural touchstones in advance with the couple — what traditions are being honored, in what order, and what context guests from each background will need to appreciate them. I can provide brief, respectful framing for customs that some guests may not recognize, so everyone in the room is included rather than confused." },
      { question: "What is the difference between a DJ and an MC, and can you be both?", answer: "A DJ manages music. An MC manages the experience of the evening — the words, the transitions, the energy of each moment. Dan's Events offers both under one roof, which eliminates the communication gap that often exists between a DJ and a separate MC. When the same person controls both the mic and the music, the evening flows with a coherence that two separate vendors rarely achieve." },
      { question: "How do you handle the unexpected — a speaker who goes too long, a moment that falls flat?", answer: "I have quiet, practiced ways to redirect a speaker who is losing the room without embarrassing them. I know how to follow a flat moment with something that lifts the energy before anyone registers what happened. The unexpected is part of every live event — the skill is handling it so smoothly that no one notices." },
    ],
  },
  "hendersonville": {
    city: "Hendersonville",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "hendersonville",
    heroTagline: "Hendersonville sits in apple country between Asheville and the Blue Ridge Parkway, and its weddings carry that same unhurried richness — ripe, warm, and full of genuine character. The hosting has to match the place.",
    introParagraph: "Hendersonville is one of those towns that feels like a secret even though it is not far from anything. The couples who marry here tend to have a specific vision — something more intimate than the big Asheville venues, more accessible than the remote mountain estates. The guest mix often skews local and familial, with deep Henderson County roots on at least one side. I bring hosting that respects that community feel while giving the evening the lift and shape it needs to become something memorable.",
    regionDescription: "Henderson County's wedding market occupies the sweet spot between the destination-wedding scale of Asheville and the intimate character of the smaller mountain towns. Its apple orchards, accessible main street, and well-kept event venues attract couples who want a celebration that feels rooted in a real place.",
    venues: [
      { name: "Expressions Event Center", location: "Hendersonville, NC", description: "A dedicated event center near downtown Hendersonville with clean, flexible spaces where the host shapes the entire character of the evening because the room itself is neutral." },
      { name: "The Barn at Chestnut Springs", location: "Hendersonville, NC", description: "A barn venue with mountain views and intimate capacity that suits family-centered receptions where the host can work at close range and let the evening feel personal from start to finish." },
      { name: "Saint Paul Mountain Vineyards", location: "Hendersonville, NC", description: "A winery venue with vineyard views where the relaxed pastoral setting invites a host to take a leisurely, storytelling-forward approach to the program." },
      { name: "Highland Lake Inn and Resort", location: "Flat Rock, NC", description: "A lakeside inn and resort just south of Hendersonville with multiple ceremony and reception settings where the multi-venue flow of the evening requires careful host coordination." },
      { name: "Flat Rock Playhouse event spaces", location: "Flat Rock, NC", description: "Event spaces associated with the State Theatre of North Carolina where the arts community context shapes a sophisticated, culture-oriented guest profile." },
      { name: "The Oklawaha Brewing Company", location: "Hendersonville, NC", description: "A craft brewery event space with an industrial-rustic character that attracts relaxed, social couples whose guests want a party more than a production." },
    ],
    nearbyAreas: ["Asheville", "Flat Rock", "Mills River", "Etowah", "Fletcher", "Brevard", "Columbus"],
    faq: [
      { question: "How do you keep smaller, intimate receptions from feeling under-produced?", answer: "Intimacy is not a limitation — it is an advantage. In a room of sixty people, every moment lands harder than in a room of two hundred. I lean into that closeness rather than compensating for it. The hosting can be more personal, the stories more specific, the transitions more deliberate." },
      { question: "Do you help write toasts or prepare speakers?", answer: "I give speakers a clear brief before the evening — how long, what to include, how I will introduce them — so they arrive prepared. If someone asks for more help, I can review what they plan to say and offer suggestions on what makes a toast land and what gets in the way." },
      { question: "What do you do during cocktail hour?", answer: "Cocktail hour is when I am gathering information, not performing. I move through the room, introduce myself to key family members, check in with the coordinator, confirm the program timeline, and get a read on the energy of the crowd. By the time guests are seated for dinner, I know the room well enough to host it accurately." },
    ],
  },
  "highlands": {
    city: "Highlands",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "highlands",
    heroTagline: "Highlands sits at 4,000 feet, above the clouds on most summer afternoons, and the weddings here carry that altitude — elevated in every sense, with guests who expect and deserve the best. The hosting must be flawless.",
    introParagraph: "Highlands is one of the most exclusive resort communities in the Southeast, and the weddings I host here are among the most demanding — in the best possible way. The guests are often well-traveled, cultured, and accustomed to excellence in hospitality. The couples are frequently from Atlanta or Charlotte or New York, choosing Highlands for its particular combination of natural beauty and discreet luxury. I bring hosting that is precise, warm, and utterly unobtrusive.",
    regionDescription: "The Highlands-Cashiers plateau has been a summer retreat for Southeastern upper-class families for generations, and that legacy shapes the wedding culture here profoundly. Families with long histories in the area expect a certain standard of grace and discretion, and the hosting must deliver on that expectation without calling attention to itself.",
    venues: [
      { name: "Old Edwards Inn and Spa", location: "Highlands, NC", description: "One of the finest boutique luxury hotels in the Southeast with meticulously designed event spaces where every detail is curated and the hosting must rise to that same level of care." },
      { name: "The Country Club of Sapphire Valley", location: "Sapphire, NC", description: "A private mountain club with spectacular views and formal event spaces where the established membership culture and discreet wealth of the guest base call for hosting that is elegant without being showy." },
      { name: "Highlands Country Club", location: "Highlands, NC", description: "A historic private club at the center of Highlands social life where the guest list often includes multiple generations of the same families and the hosting must honor those relationships gracefully." },
      { name: "Half Mile Farm", location: "Highlands, NC", description: "A boutique inn with beautifully landscaped grounds and outdoor ceremony spaces where the hosting navigates al fresco elegance and must be sensitive to weather-driven energy shifts." },
      { name: "Clear Creek Farm", location: "Highlands, NC", description: "A private estate and farm venue that offers a naturalistic luxury-pastoral setting where the informal elegance of the space rewards a host who can be sophisticated without being formal." },
      { name: "Skyline Lodge", location: "Highlands, NC", description: "A hilltop lodge with sweeping views of the Highlands plateau where the setting does much of the work and the host's job is to complement the beauty with moments that feel equally extraordinary." },
    ],
    nearbyAreas: ["Cashiers", "Sapphire", "Glenville", "Franklin", "Brevard", "Walhalla SC", "Clayton GA"],
    faq: [
      { question: "How do you host for very high-net-worth guests who have seen everything?", answer: "The answer is subtlety and specificity. Guests who have attended extraordinary events are not impressed by production for its own sake — they notice the quality of the person behind the microphone, the precision of the timing, the warmth of how a moment is set up. I bring craft, not flash." },
      { question: "What if the couple wants a very private, low-key celebration without much hosting?", answer: "I can host a dinner that feels like no one is hosting it — all the logistics handled invisibly, only speaking when necessary, letting the natural flow of conversation and connection do the work." },
      { question: "Do you have experience with black-tie or formal evening receptions?", answer: "Yes. Black-tie receptions require a specific register — restrained, precise, and quietly commanding. The pacing is slower, the language more deliberate, the transitions cleaner. I have hosted formal evening receptions at the level these communities expect." },
    ],
  },
  "johnson-city": {
    city: "Johnson City",
    state: "Tennessee",
    stateAbbr: "TN",
    slug: "johnson-city",
    heroTagline: "Johnson City weddings happen in the shadow of the Appalachians on the Tennessee side — hearty, genuine, and full of people who show up for each other without needing a reason. The hosting honors that.",
    introParagraph: "Johnson City is the hub of the Tri-Cities area of northeast Tennessee, anchored by East Tennessee State University and surrounded by some of the most beautiful mountain terrain in the region. The couples I work with here tend to be grounded, community-oriented, and deeply connected to extended family networks. The guest list at a Johnson City wedding is often half family and half long-term friends — people who have known each other for decades. My job is to give those relationships a stage for one night.",
    regionDescription: "The Tri-Cities region — Johnson City, Kingsport, and Bristol — shares an Appalachian wedding culture built on community, family, and genuine generosity. The area has a strong church and faith tradition that often shapes wedding programs, and the hosting must be fluent in that register without being exclusive to it.",
    venues: [
      { name: "Carnegie Hotel", location: "Johnson City, TN", description: "A boutique luxury hotel in downtown Johnson City with elegant ballrooms and refined service where the hosting can be more formal and deliberate than in the surrounding rural venues." },
      { name: "The Pavilion at Hunter Valley Farm", location: "Johnson City, TN", description: "A farm venue with mountain backdrop and barn-style pavilion where the agricultural setting invites warmth, community, and a host who feels at home in both worlds." },
      { name: "Willow Springs Barn", location: "Jonesborough, TN", description: "A barn venue near the historic town of Jonesborough where the Appalachian storytelling tradition of Tennessee's oldest town adds resonance to every moment a host creates." },
      { name: "Ridgewood Event Center", location: "Johnson City, TN", description: "A local event center with flexible spaces that accommodates the full range of Johnson City receptions — from formal seated dinners to open floor-plan celebrations." },
      { name: "The Tipton-Haynes Historic Site", location: "Johnson City, TN", description: "A historic property with outdoor event spaces where the deep historical roots of the site create a specific atmosphere that rewards a host who can honor the place while keeping the evening alive." },
      { name: "Tweetsie Trail and Watauga River corridor private venues", location: "Johnson City / Elizabethton, TN", description: "Private estate venues along the Watauga River where natural beauty drives the choice and the host must complement rather than compete with the setting." },
    ],
    nearbyAreas: ["Kingsport", "Bristol", "Elizabethton", "Jonesborough", "Erwin", "Greeneville", "Boone NC"],
    faq: [
      { question: "How do you incorporate faith into the hosting without making non-religious guests feel excluded?", answer: "I follow the couple's lead on how much faith language belongs in the reception hosting. If the blessing is important, I introduce it with warmth and give everyone in the room permission to participate in whatever way feels right to them. I do not editorialize either way." },
      { question: "What if several members of the wedding party want to give toasts?", answer: "Multiple toasts are manageable with good structure. I work with the couple to sequence the speakers, cap the total time, and brief each speaker on length expectations. Then I frame each toast individually so it arrives with the right emotional setup." },
      { question: "How early do you arrive on the wedding day?", answer: "I arrive at least ninety minutes before the reception begins. That time is for sound checks, walking the room, confirming the program with the coordinator, and being present for the couple during final preparations. Arriving early is not optional for me — it is where the quality of the evening is built." },
    ],
  },
  "knoxville": {
    city: "Knoxville",
    state: "Tennessee",
    stateAbbr: "TN",
    slug: "knoxville",
    heroTagline: "Knoxville weddings carry the energy of a city that takes pride in its Tennessee identity — football Saturdays, Smokies weekends, a downtown that has found itself again. That pride of place is something a great host can work with.",
    introParagraph: "Knoxville is a genuine city with genuine personality, and its wedding scene has grown into something sophisticated over the past decade. The University of Tennessee community, the Old City arts district, and the surrounding East Tennessee families create a diverse guest mix that I genuinely enjoy hosting. Knoxville crowds are warm and social — they want to have a good time and they give you permission to take them there.",
    regionDescription: "East Tennessee's largest city anchors a regional wedding market that extends from the Smokies foothills to the lakefront communities along the Tennessee River reservoirs. Knoxville's wedding culture blends strong university ties, Appalachian family traditions, and an emerging urban sophistication.",
    venues: [
      { name: "The Mill and Mine", location: "Knoxville, TN", description: "A massive converted industrial space in the Old City with two levels and a reputation for large, energetic events where the host must command significant physical scale while keeping the evening personal." },
      { name: "Rothchild Catering and Conference Center", location: "Knoxville, TN", description: "A full-service event venue with traditional ballrooms and a professional catering operation where the hosting works in concert with a highly organized service team." },
      { name: "The Foundry", location: "Knoxville, TN", description: "A historic World's Fair venue with exposed industrial architecture and flexible event space where the mix of history and creative energy suits couples who want something unexpected." },
      { name: "Knoxville Museum of Art", location: "Knoxville, TN", description: "A contemporary art museum with elegant event spaces where the hosting competes with and complements the visual environment — guests appreciate a host who can match the sophistication of the setting." },
      { name: "Oliver Hotel", location: "Knoxville, TN", description: "A boutique hotel in the heart of downtown Knoxville with intimate event spaces that suit smaller, design-forward receptions where every detail counts." },
      { name: "Whitestone Country Inn", location: "Kingston, TN", description: "A lakeside inn on Watts Bar Lake with gardens and indoor reception spaces where the waterfront setting creates a peaceful, romantic atmosphere that the hosting should support rather than overwhelm." },
      { name: "Mead's Quarry", location: "Knoxville, TN", description: "An outdoor venue at a former stone quarry with a wild, natural beauty that attracts adventurous couples and guests who respond to a host who can hold the outdoors." },
    ],
    nearbyAreas: ["Maryville", "Oak Ridge", "Clinton", "Lenoir City", "Sevierville", "Gatlinburg", "Kingston"],
    faq: [
      { question: "How do you keep a party crowd engaged through the formal parts of the evening?", answer: "By not asking them to endure formality longer than necessary. The formal elements land best when they are well-paced, properly set up, and clearly bounded. When guests know a formal moment is coming and then see it executed beautifully, they give it full attention. Then you release them back to the party." },
      { question: "What is your approach to crowd energy — how do you build it across the evening?", answer: "The evening has a shape, and I work within it. Early on, energy is social. The formal program channels that energy through the toasts and first dances. After that, the floor opens and the energy becomes kinetic. My job is to move the room from one register to the next without jarring shifts." },
      { question: "Do you take requests from guests during the program?", answer: "I stay in contact with the couple throughout the evening, and if a family member or guest has a request that fits the program, I consider it. But I do not run the evening by committee. The couple and I have a plan, and departing from it requires a good reason." },
    ],
  },
  "lake-lure": {
    city: "Lake Lure",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "lake-lure",
    heroTagline: "Lake Lure is one of those places that stops you — the water, the mountains reflected in it, the particular stillness of the air in the gorge. The hosting has to be worthy of what the setting is doing.",
    introParagraph: "Lake Lure and Chimney Rock are tucked into the Hickory Nut Gorge, one of the most dramatic natural settings in North Carolina. The couples who choose to marry here are often making a statement about beauty and intimacy — they want something that feels discovered rather than designed. The guest lists tend to be smaller and more intentional. I bring hosting that honors that intimacy, working in close quarters with warmth and precision.",
    regionDescription: "The Lake Lure and Chimney Rock area has a devoted following among couples who want mountain and water in the same frame. The gorge's relatively intimate venue ecosystem means most receptions feel personal by default — the hosting amplifies that quality rather than having to manufacture it.",
    venues: [
      { name: "Rumbling Bald on Lake Lure", location: "Lake Lure, NC", description: "A resort on the lakeshore with ballrooms and outdoor ceremony spaces where the water views create a naturally romantic atmosphere and the host shapes the evening within that visual abundance." },
      { name: "The Lodge on Lake Lure", location: "Lake Lure, NC", description: "A boutique lakeside inn with intimate event capacity where small receptions feel personal from the first moment and the host can work without amplification in the quieter indoor settings." },
      { name: "Esmeralda Inn and Restaurant", location: "Chimney Rock, NC", description: "A historic inn in the heart of the gorge with a romantic, old-world character that suits small, intimate receptions where the atmosphere does most of the heavy lifting." },
      { name: "Flowering Bridge Garden", location: "Lake Lure, NC", description: "An outdoor garden venue on the lake's edge where ceremony and reception flow into the natural landscape and the host works with the environment rather than containing it." },
      { name: "Lake Lure Town Beach and Pavilion", location: "Lake Lure, NC", description: "The town's public waterfront pavilion hosts outdoor celebrations where the community character of the setting invites a casual, joyful hosting style." },
      { name: "Chimney Rock State Park adjacent private venues", location: "Chimney Rock, NC", description: "Private properties near the base of Chimney Rock where the dramatic gorge geography creates a backdrop that makes every moment feel slightly larger than life." },
    ],
    nearbyAreas: ["Chimney Rock", "Bat Cave", "Rutherfordton", "Spindale", "Hendersonville", "Tryon", "Forest City"],
    faq: [
      { question: "How do you handle hosting in a small venue where you are very close to the guests?", answer: "Close quarters change the hosting dynamic completely. In a small room, you lower the performance register and raise the personal register. I speak more conversationally, work without excessive amplification, and let the intimacy of the space do the work that staging and lighting do in a large ballroom." },
      { question: "What if the weather affects an outdoor ceremony or reception?", answer: "Weather is part of outdoor events, and I prepare for it. I always have a rain contingency in the program and I stay in communication with the venue coordinator about backup plans. When weather forces a change, a calm, clear host is what keeps guests from feeling anxious." },
      { question: "Can you host a very small wedding — thirty people or fewer?", answer: "Yes, and small weddings are some of my favorite evenings. At that scale, the hosting is entirely conversational — less announcement, more storytelling. Every person in the room can be acknowledged. The toasts feel like toasts among friends rather than performances." },
    ],
  },
  "spartanburg": {
    city: "Spartanburg",
    state: "South Carolina",
    stateAbbr: "SC",
    slug: "spartanburg",
    heroTagline: "Spartanburg weddings are rooted in the Upstate South Carolina tradition of showing up fully — church family, blood family, and the friends who have been around long enough to count as both. The hosting honors that loyalty.",
    introParagraph: "Spartanburg is a Upstate South Carolina city with deep civic pride and a community ethos that shows up in how people celebrate. The families I encounter here are often multi-generational Spartanburg residents who know each other through church, school, and decades of shared history. That kind of room has enormous warmth and enormous expectations — they can tell when someone is genuinely present for them and when someone is just working through a checklist.",
    regionDescription: "Spartanburg County's wedding market is anchored by strong community ties and an increasingly diverse population driven by BMW and related manufacturing investment. The result is a wedding culture that spans traditional Southern Baptist families, upwardly mobile professional couples, and an international community that brings its own rich traditions.",
    venues: [
      { name: "Chapman Cultural Center", location: "Spartanburg, SC", description: "A multipurpose arts center with event spaces that draw culturally engaged couples and guests who appreciate a host with awareness and context." },
      { name: "1 North Church Street", location: "Spartanburg, SC", description: "A downtown Spartanburg event venue with classical details and flexible layout where the formality of the space rewards precise, elegant hosting." },
      { name: "The Showroom at Headquarters Building", location: "Spartanburg, SC", description: "A downtown event space with urban industrial character that attracts Spartanburg's younger professional class and couples who want a modern, curated reception environment." },
      { name: "The Boiling Springs area barn venues", location: "Boiling Springs, SC", description: "Rural barn and farm venues south of Spartanburg where the agricultural setting and multigenerational family guest lists call for down-to-earth, heartfelt hosting." },
      { name: "Hub City Farmers Market event space", location: "Spartanburg, SC", description: "A community-oriented event venue in the heart of Spartanburg where the local community-first character of the space shapes a relaxed and genuine hosting approach." },
      { name: "Hollywild Animal Park event spaces", location: "Wellford, SC", description: "A unique outdoor venue near Spartanburg where the unconventional setting attracts adventurous couples and guests who are already primed for something out of the ordinary." },
    ],
    nearbyAreas: ["Greenville", "Gaffney", "Boiling Springs", "Duncan", "Inman", "Landrum", "Chesnee"],
    faq: [
      { question: "How do you handle guests who are emotionally invested and want to participate beyond their toast?", answer: "A highly engaged guest community is a gift, not a problem. I channel that investment through the program — building in moments that invite the room's participation, structuring toasts so the love in the room can be expressed cleanly, and reading when a moment of spontaneous feeling should be honored rather than redirected." },
      { question: "What if the couple has very specific ideas about every moment of the evening?", answer: "Specific couples are my favorite clients to work with. The more detailed the vision, the more precisely I can deliver it. I document everything we discuss, confirm it in writing before the wedding, and execute it exactly." },
      { question: "Can you handle bilingual hosting elements?", answer: "I can incorporate bilingual framing into a program where specific moments need acknowledgment in another language, and I work with the couple to identify those moments in advance." },
    ],
  },
  "waynesville": {
    city: "Waynesville",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "waynesville",
    heroTagline: "Waynesville is mountain North Carolina without the crowds — quiet, genuine, and full of a particular kind of beauty that earns your trust slowly. The weddings here feel the same way.",
    introParagraph: "Waynesville and the surrounding Haywood County communities are where couples come when they want the mountains without the Asheville scene. The town's arts community, Celtic heritage, and strong local roots shape a distinctive wedding culture that I find genuinely compelling. Guest lists here often include deep Appalachian family networks mixed with artists, educators, and out-of-town friends discovering the area for the first time. I bring hosting that bridges those worlds naturally.",
    regionDescription: "Haywood County sits at the heart of the southern Appalachians, with the Blue Ridge Parkway to the north and Great Smoky Mountains National Park to the west. The area's wedding culture is intimate and community-centered, influenced by the annual Folkmoot international festival and a strong pride in Appalachian heritage.",
    venues: [
      { name: "Waynesville Inn Golf Resort and Spa", location: "Waynesville, NC", description: "A mountain resort with ballrooms and garden event spaces where the established hospitality of the property provides a comfortable baseline and the hosting builds on it." },
      { name: "Balsam Mountain Inn", location: "Balsam, NC", description: "A historic Victorian-era inn on the highest railroad point east of the Rockies with sweeping mountain views and intimate event capacity where the setting's historic weight asks for equally considered hosting." },
      { name: "The Swag", location: "Waynesville, NC", description: "A remote, exclusive mountaintop inn with limited guest capacity and extraordinary views where small, intimate weddings unfold with a privacy and presence that is rare anywhere." },
      { name: "Boyd Farm", location: "Waynesville, NC", description: "A working farm venue with pastoral mountain views where the agricultural roots of the setting invite unpretentious, heartfelt hosting that matches the land." },
      { name: "Maggie Valley resort venues", location: "Maggie Valley, NC", description: "Resort and event venues in the neighboring valley that share Waynesville's mountain character while offering additional capacity for larger family celebrations." },
      { name: "Crystal Springs area private estates", location: "Haywood County, NC", description: "Private estate venues near the famous rhododendron blooms of the Blue Ridge where the natural spectacle of the region becomes part of the evening's identity." },
    ],
    nearbyAreas: ["Maggie Valley", "Canton", "Clyde", "Bryson City", "Sylva", "Asheville", "Cherokee"],
    faq: [
      { question: "How do you honor Appalachian and mountain traditions in your hosting?", answer: "Mountain communities carry deep traditions of hospitality, storytelling, and community ritual. I honor them genuinely rather than performing them. If there are specific family customs, music traditions, or community rituals that matter to a couple in Haywood County, I build those in with the same care I bring to any other element of the program." },
      { question: "What if the venue is remote and sound system options are limited?", answer: "Remote venues require planning. I bring backup amplification equipment for situations where the venue's systems are inadequate, and I scope the acoustic situation during advance visits whenever possible. In an intimate outdoor setting with limited sound support, I adjust the hosting style to work with the natural acoustic rather than against it." },
      { question: "How do you create energy at a smaller mountain wedding without it feeling forced?", answer: "Energy at a small wedding comes from connection, not performance. I focus on authentic shared experiences — a well-told story, a toast that says exactly the right thing, a moment of humor that lands because it is true. That kind of energy is real, and it does not require a DJ drop to create it." },
    ],
  },
  "winston-salem": {
    city: "Winston-Salem",
    state: "North Carolina",
    stateAbbr: "NC",
    slug: "winston-salem",
    heroTagline: "Winston-Salem is a city with a deep art soul and a practical heart — it funds the symphony and knows how to make things. The weddings here carry both: cultured and grounded, never one without the other.",
    introParagraph: "Winston-Salem is one of North Carolina's most underrated cities for weddings. The arts community centered on Wake Forest University and the North Carolina School of the Arts creates a guest pool with genuine cultural sophistication. At the same time, the old Reynolds and Hanes family ties and the Moravian heritage of Old Salem give the city a deep-rooted community identity. I navigate that combination carefully — bringing hosting that respects the cultural intelligence of this room while honoring the warmth and tradition underneath it.",
    regionDescription: "The Piedmont Triad's western anchor has a distinct personality shaped by Moravian settlement history, tobacco-era wealth, and a contemporary investment in the arts that has positioned the city as a creative hub in the Carolinas. Winston-Salem couples often want their celebrations to reflect that layered identity, and the hosting needs to be sophisticated enough to honor it.",
    venues: [
      { name: "Graylyn Estate", location: "Winston-Salem, NC", description: "A 1932 Norman Revival estate on 55 acres that serves as one of the finest event venues in the South; the grandeur of the architecture requires hosting that is equally considered and precise." },
      { name: "Millennium Center", location: "Winston-Salem, NC", description: "A downtown event center in a historic building with dramatic architectural details where the imposing scale of the space requires a host who can fill it without overwhelming it." },
      { name: "Brookstown Inn", location: "Winston-Salem, NC", description: "A boutique hotel converted from an 1837 cotton mill with intimate event spaces where the historic character of the building creates a warm, textured backdrop for evening celebrations." },
      { name: "Old Salem Museums and Gardens event spaces", location: "Winston-Salem, NC", description: "A living history museum with event spaces set within the Moravian village where the weight of 18th-century history adds a specific gravitas to celebrations held there." },
      { name: "The Kimpton Cardinal Hotel", location: "Winston-Salem, NC", description: "A boutique luxury hotel in a converted 1929 office building with design-forward event spaces that attract couples with a strong aesthetic sensibility and guests who notice the difference." },
      { name: "Forsyth Country Club", location: "Winston-Salem, NC", description: "A traditional private club where old Winston-Salem family networks converge and the hosting must navigate deep familiarity and established social hierarchies with grace." },
      { name: "Hanes Mansion at Reynolda Village", location: "Winston-Salem, NC", description: "An estate venue connected to the historic Reynolda House and gardens where the legacy of the Reynolds family and the grandeur of the grounds shape a particular atmosphere of cultured elegance." },
    ],
    nearbyAreas: ["Greensboro", "High Point", "Clemmons", "Kernersville", "Lewisville", "Mocksville", "Mount Airy"],
    faq: [
      { question: "How do you host for an arts-educated crowd that is skeptical of cliché?", answer: "By being genuinely original rather than performing originality. Arts communities are quick to detect formula, and the worst thing I can do is try to seem creative. Instead, I do the work of understanding this specific couple's story and building hosting that is specific to them — no borrowed phrases, no generic sentiments, no moments that could belong to any other wedding." },
      { question: "Can you incorporate music or arts references into the hosting?", answer: "Yes, and when a couple has a genuine connection to music, literature, or another art form, I build those references in with care. The key is that every reference must be true to the couple — it cannot feel imported or decorative." },
      { question: "How do you approach Moravian or other historical traditions that Winston-Salem couples sometimes want to honor?", answer: "I research the traditions that matter to each couple specifically rather than relying on general knowledge. Traditions honored with accuracy and genuine respect land completely differently than traditions nodded to casually." },
    ],
  },
};
